# Generated by Django 4.2.20 on 2025-03-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state_zip', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=10)),
                ('square_feet', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('year_renovated', models.IntegerField()),
            ],
        ),
    ]
