# Generated by Django 4.2.20 on 2025-03-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
