# Generated by Django 4.2.20 on 2025-03-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_filter', '0002_car_description_car_drivetrain_car_name_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
    ]
