# Generated by Django 4.2.20 on 2025-03-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_filter', '0003_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.CharField(max_length=7),
        ),
    ]
