# Generated by Django 4.2.20 on 2025-03-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_filter', '0005_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(max_length=7),
        ),
    ]
